apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-uptime-kuma-web-egress
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      app: uptime-kuma
  egress:
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "80"
              protocol: TCP
            - port: "443"
              protocol: TCP
