apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tenant-platform.operatorServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tenant-operator-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch

  - apiGroups: [""]
    resources:
      - pods/log
    verbs:
      - get

  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.tenant.name }}-operator-readonly
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "tenant-platform.operatorServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: tenant-operator-readonly
