apiVersion: v1
kind: ServiceAccount
metadata:
  name: uptime-kuma
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tenant-platform.labels" . | nindent 4 }}
automountServiceAccountToken: false
